### ISSUE TITLE
Provide fixture(s)

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/behave-webdriver#30]
Provide fixtures for setup/cleanup of the driver.

**Comment by jrd** [comment]
What have you in mind?

**Comment by spyoungtech** [comment]
Something similar to what is described in the [behave fixture documentation](http://behave.readthedocs.io/en/latest/fixtures.html#providing-a-fixture) is probably what we're looking for.

Currently, users are expected to provide the driver setup/cleanup logic in their environment.py file themselves. It would be nice if we could provide fixtures to make this easier.

**Comment by spyoungtech** [comment]
In addition, or perhaps as an alternative, we could also do something like what [`behave_http`](https://github.com/mikek/behave-http) does and just provide a `before_all` function that one simply imports to their `environment.py` file

**Comment by jrd** [comment]
I think you might provide the second form.

This way one could choose if it want to use it for a `before_all`, a `before_feature` or anything else. One can also want to do other things in those methods so a factory seems good.

For instance, I initiate the web browser driver in the `before_feature` method with two fixtures:
- `browser` which is just a special driver that use your `BehaveDriverMixin` with some additions
- `webdriver_steps` thats just assign `ctx.browser` to `ctx.behave_driver` for using your steps.

**Comment by spyoungtech** [comment]
resolved by #51
