### ISSUE TITLE
Discerning CSS selectors from xpath needs improvement

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/behave-webdriver#31]
The idea is to support locating elements both by CSS selectors and xpath for all the step definitions dealing with elements.

The [current logic](https://github.com/spyoungtech/behave-webdriver/blob/c0ce59083396693c71372af7945572cb626586cf/behave_webdriver/__init__.py#L197)  is simple but incomplete, since it will only work if the xpath starts with `//`. However, xpaths don't necessarily have to start like this. It would be ideal if we could implement a better way to differentiate xpath versus CSS selectors in locating elements.

IIRC, the way cucumer-boilerplate does this is it simply tries one first to see if a result is found, then tries another. This may be a better approach than the current method we're using now.

Also note the same logic is repeated in the [wait_for_element_condition](https://github.com/spyoungtech/behave-webdriver/blob/c0ce59083396693c71372af7945572cb626586cf/behave_webdriver/__init__.py#L587) method.

**Comment by jrd** [comment]
Checking for `/` seems ok to me too. Steps element search always do the search from the entire document, not from a starting element point.

Some may want to check for an element anywhere within the document, hence they will use an expression starting with `//`.

Some may want to provide a full path to an element so the expression will probably starts with `/html/body/` or someting

No CSS selector I know of could start with a `/`, so checking if the expression starts with a `/` seems ok to me.

**Comment by spyoungtech** [comment]
resolved in #52
