### ISSUE TITLE
How to add firefox_profile into the behave.webdriver framework

### ISSUE THREAD

**Issue by dhan123456** [spyoungtech/behave-webdriver#81]
I want to set the preferences for the firefox_profile in wedriver.Firefox(firefox_profile=).
Where and how do i incorporate it into the framework ?

**Comment by spyoungtech** [comment]
Hi @dhan123456 this would work the same was as with the normal Firefox driver!

The firefox driver in this library is a subclass of the selenium firefox driver, so it's fully compatible with anything you can do with selenium.

**Comment by spyoungtech** [comment]
Going to close for now. Let me know if you have any further questions with this!
