### ISSUE TITLE
The step "When I clear the inputfield "{element}" doesn't work in Chrome

### ISSUE THREAD

**Issue by peterkurishev** [spyoungtech/behave-webdriver#83]
When you use "I clear the inputfiled "{element}" step with Chrome webdriver the field doesn't clears, but you can still add the contents to it.

**Comment by spyoungtech** [comment]
@peterkurishev thanks for reporting this. Can you describe the OS you are using and the version of chrome and chromedriver you are using?

This library runs tests against chrome, and the tests are currently passing for stable version of Chrome on linux.

It may have something to do with the particular site you are using, too.
